parameters:
  env(WKHTMLTOPDF_PATH): '/usr/local/bin/wkhtmltopdf'
  env(WKHTMLTOIMAGE_PATH): '/usr/local/bin/wkhtmltoimage'

knp_snappy:
  pdf:
    enabled:    true
    binary:     '%env(WKHTMLTOPDF_PATH)%'
    options:    []
  image:
    enabled:    true
    binary:     '%env(WKHTMLTOIMAGE_PATH)%'
    options:    []
  temporary_folder: '%kernel.cache_dir%/snappy'
