knp_snappy:
  pdf:
    enabled:    true
    binary:     "wkhtmltopdf"
    options:    []
  image:
    enabled:    true
    binary:     '%env(WKHTMLTOIMAGE_PATH)%'
    options:    []
  temporary_folder: '%kernel.cache_dir%/snappy'